-- Code generated by go-crudgen; DO NOT EDIT.

-- +goose Up
-- +goose StatementBegin
CREATE TABLE posts (
    id UUID NOT NULL PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT,
    published BOOLEAN DEFAULT FALSE,
    author UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE posts;
-- +goose StatementEnd
