-- Code generated by go-crudgen; DO NOT EDIT.

-- +goose Up
-- +goose StatementBegin
CREATE TABLE authors (
    id UUID NOT NULL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE authors;
-- +goose StatementEnd
