package integration

import (
	"bytes"
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"io"
	"net/http"
	"net/http/httptest"
	"strconv"
	"testing"
	"time"

	"example.com/blogservice/internal/blog"
	"example.com/blogservice/internal/blog/postgres"
	"example.com/blogservice/internal/blog/restapi"

	"github.com/google/uuid"
	"github.com/pressly/goose/v3"
	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go"
	tcpostgres "github.com/testcontainers/testcontainers-go/modules/postgres"
	"github.com/testcontainers/testcontainers-go/wait"
)

// TestIntegration drives the generated service against a real PostgreSQL instance
// started with testcontainers: it applies the generated goose migrations, wires
// the generated Postgres repositories into the router, and exercises the HTTP API
// end to end. A Docker daemon is required.
func TestIntegration(t *testing.T) {
	dsn := startPostgres(t)

	db, err := postgres.NewDB(dsn)
	require.NoError(t, err, "NewDB")
	t.Cleanup(func() { _ = db.Close() })

	// Apply the generated migrations through goose itself, proving the generated
	// goose files parse and the DDL is valid Postgres.
	require.NoError(t, goose.SetDialect("postgres"))
	require.NoError(t, goose.Up(db.DB, "../internal/blog/migrations"), "goose up")

	srv := httptest.NewServer(restapi.NewRouter(restapi.Deps{
		Posts:    postgres.NewPostRepository(db),
		Authors:  postgres.NewAuthorRepository(db),
		Comments: postgres.NewCommentRepository(db),
		Tags:     postgres.NewTagRepository(db),
	}))
	t.Cleanup(srv.Close)

	// Subtests share one container and run in order (no t.Parallel): the down
	// migration must come last because it drops the tables the others rely on.

	t.Run("CRUD round-trips through Postgres", func(t *testing.T) {
		// The post's author column has a foreign key to authors(id), so the author
		// must exist before a post can reference it.
		var author blog.Author
		do(t, srv, http.MethodPost, "/authors",
			restapi.CreateAuthorRequest{Email: "ada@example.com", Name: new("Ada")},
			&author, http.StatusCreated)
		require.NotEqual(t, uuid.Nil, author.ID, "id is generated by the DB")
		authorID := author.ID

		var created blog.Post
		do(t, srv, http.MethodPost, "/posts",
			restapi.CreatePostRequest{Title: "Hello", Body: new("world"), Author: &authorID},
			&created, http.StatusCreated)
		require.NotEqual(t, uuid.Nil, created.ID, "id is generated by the DB")
		require.Equal(t, "world", *created.Body)
		require.False(t, created.Published, "published takes its default")
		require.False(t, created.CreatedAt.IsZero(), "created_at is populated by the DB")
		idPath := "/posts/" + created.ID.String()

		var got blog.Post
		do(t, srv, http.MethodGet, idPath, nil, &got, http.StatusOK)
		require.Equal(t, "Hello", got.Title)
		require.Equal(t, "world", *got.Body)
		require.Equal(t, authorID, *got.Author)

		var updated blog.Post
		do(t, srv, http.MethodPut, idPath,
			restapi.UpdatePostRequest{Title: "Updated", Body: new("body2"), Author: &authorID},
			&updated, http.StatusOK)
		require.Equal(t, "Updated", updated.Title)
		require.Equal(t, "body2", *updated.Body)
		require.True(t, created.CreatedAt.Equal(updated.CreatedAt), "update keeps created_at")

		do(t, srv, http.MethodDelete, idPath, nil, nil, http.StatusNoContent)
		do(t, srv, http.MethodGet, idPath, nil, nil, http.StatusNotFound)
	})

	t.Run("nullable fields round-trip as NULL", func(t *testing.T) {
		// Body and Author are omitted, so they must be stored and returned as NULL
		// (nil pointers) - the sql.Null[T] round-trip on the repository row.
		var created blog.Post
		do(t, srv, http.MethodPost, "/posts",
			restapi.CreatePostRequest{Title: "No body"},
			&created, http.StatusCreated)
		require.Nil(t, created.Body)
		require.Nil(t, created.Author)

		var got blog.Post
		do(t, srv, http.MethodGet, "/posts/"+created.ID.String(), nil, &got, http.StatusOK)
		require.Equal(t, "No body", got.Title)
		require.Nil(t, got.Body, "a NULL column must decode back to a nil pointer")
		require.Nil(t, got.Author)
	})

	t.Run("list returns persisted posts", func(t *testing.T) {
		var list cursorPage[blog.Post]
		do(t, srv, http.MethodGet, "/posts?limit=10", nil, &list, http.StatusOK)
		require.NotEmpty(t, list.Items)
	})

	t.Run("list filters, orders and pages in SQL", func(t *testing.T) {
		var author blog.Author
		do(t, srv, http.MethodPost, "/authors", restapi.CreateAuthorRequest{Email: "sorted@example.com"}, &author, http.StatusCreated)
		for _, req := range []restapi.CreatePostRequest{
			{Title: "Beta", Author: &author.ID, Views: new(int64(2))},
			{Title: "Alpha", Author: &author.ID, Views: new(int64(3)), Published: new(true)},
			{Title: "Gamma", Author: &author.ID, Views: new(int64(1))},
		} {
			do(t, srv, http.MethodPost, "/posts", req, nil, http.StatusCreated)
		}

		titles := func(query string) []string {
			var list cursorPage[blog.Post]
			do(t, srv, http.MethodGet, "/posts?author="+author.ID.String()+query, nil, &list, http.StatusOK)
			out := make([]string, len(list.Items))
			for i, p := range list.Items {
				out[i] = p.Title
			}
			return out
		}
		require.Equal(t, []string{"Beta", "Alpha", "Gamma"}, titles(""))
		require.Equal(t, []string{"Gamma", "Alpha", "Beta"}, titles("&dir=desc"))
		require.Equal(t, []string{"Alpha"}, titles("&published=true"))
		require.Equal(t, []string{"Beta"}, titles("&published=false&limit=1"))

		walk := func(query string) []string {
			var out []string
			path := "/posts?author=" + author.ID.String() + "&limit=1" + query
			next := path
			for range 10 {
				var list cursorPage[blog.Post]
				do(t, srv, http.MethodGet, next, nil, &list, http.StatusOK)
				for _, p := range list.Items {
					out = append(out, p.Title)
				}
				if list.NextCursor == "" {
					return out
				}
				next = path + "&cursor=" + list.NextCursor
			}
			require.Fail(t, "cursor walk did not end", query)
			return nil
		}
		require.Equal(t, []string{"Beta", "Alpha", "Gamma"}, walk(""))
		require.Equal(t, []string{"Gamma", "Alpha", "Beta"}, walk("&dir=desc"))
		require.Equal(t, []string{"Beta", "Gamma"}, walk("&published=false"))
	})

	t.Run("constraint violations map to client errors", func(t *testing.T) {
		const email = "grace@example.com"

		var author blog.Author
		do(t, srv, http.MethodPost, "/authors",
			restapi.CreateAuthorRequest{Email: email},
			&author, http.StatusCreated)
		do(t, srv, http.MethodPost, "/posts",
			restapi.CreatePostRequest{Title: "Referencing", Author: &author.ID},
			nil, http.StatusCreated)

		cases := []struct {
			name    string
			method  string
			path    string
			body    any
			status  int
			wantErr error
		}{
			{"duplicate unique field", http.MethodPost, "/authors", restapi.CreateAuthorRequest{Email: email}, http.StatusConflict, blog.ErrAlreadyExists},
			{"unknown reference", http.MethodPost, "/posts", restapi.CreatePostRequest{Title: "Orphan", Author: new(uuid.New())}, http.StatusUnprocessableEntity, blog.ErrReferenceNotFound},
			{"delete referenced entity", http.MethodDelete, "/authors/" + author.ID.String(), nil, http.StatusConflict, blog.ErrStillReferenced},
		}

		for _, tc := range cases {
			t.Run(tc.name, func(t *testing.T) {
				var got apiError
				do(t, srv, tc.method, tc.path, tc.body, &got, tc.status)
				require.NotEmpty(t, got.Code)
				require.Equal(t, tc.wantErr.Error(), got.Message)
			})
		}
	})

	t.Run("scalar types round-trip", func(t *testing.T) {
		bornOn := blog.Date(time.Date(1815, time.December, 10, 0, 0, 0, 0, time.UTC))
		var author blog.Author
		do(t, srv, http.MethodPost, "/authors",
			restapi.CreateAuthorRequest{Email: "lovelace@example.com", BornOn: &bornOn},
			&author, http.StatusCreated)

		var gotAuthor blog.Author
		do(t, srv, http.MethodGet, "/authors/"+author.ID.String(), nil, &gotAuthor, http.StatusOK)
		require.True(t, time.Time(bornOn).Equal(time.Time(*gotAuthor.BornOn)))

		metadata := jsontext.Value(`{"tags":["go"]}`)
		var post blog.Post
		do(t, srv, http.MethodPost, "/posts",
			restapi.CreatePostRequest{Title: "Typed", Views: new(int64(7)), Metadata: &metadata},
			&post, http.StatusCreated)

		var gotPost blog.Post
		do(t, srv, http.MethodGet, "/posts/"+post.ID.String(), nil, &gotPost, http.StatusOK)
		require.Equal(t, int64(7), gotPost.Views)
		require.JSONEq(t, string(metadata), string(*gotPost.Metadata))
	})

	t.Run("comments use identity keys and defaults and cascade with their post", func(t *testing.T) {
		var post blog.Post
		do(t, srv, http.MethodPost, "/posts", restapi.CreatePostRequest{Title: "Commented"}, &post, http.StatusCreated)

		before := time.Now()
		var first, second blog.Comment
		do(t, srv, http.MethodPost, "/comments", restapi.CreateCommentRequest{Post: post.ID, Body: "First"}, &first, http.StatusCreated)
		do(t, srv, http.MethodPost, "/comments", restapi.CreateCommentRequest{Post: post.ID, Body: "Second"}, &second, http.StatusCreated)
		require.Positive(t, first.ID)
		require.Greater(t, second.ID, first.ID, "ids come from IDENTITY")
		require.Zero(t, first.Likes)
		require.WithinDuration(t, before, first.PostedAt, time.Minute)

		var page offsetPage[blog.Comment]
		do(t, srv, http.MethodGet, "/comments?post="+post.ID.String()+"&limit=1", nil, &page, http.StatusOK)
		require.Len(t, page.Items, 1)
		require.True(t, page.HasMore)

		firstPath := "/comments/" + strconv.FormatInt(first.ID, 10)
		do(t, srv, http.MethodDelete, firstPath, nil, nil, http.StatusNoContent)
		do(t, srv, http.MethodGet, firstPath, nil, nil, http.StatusNotFound)
		do(t, srv, http.MethodDelete, firstPath, nil, nil, http.StatusNotFound)

		var list offsetPage[blog.Comment]
		do(t, srv, http.MethodGet, "/comments?post="+post.ID.String(), nil, &list, http.StatusOK)
		require.Len(t, list.Items, 1)
		require.Equal(t, second.ID, list.Items[0].ID)

		do(t, srv, http.MethodDelete, "/posts/"+post.ID.String(), nil, nil, http.StatusNoContent)
		do(t, srv, http.MethodGet, "/comments/"+strconv.FormatInt(second.ID, 10), nil, nil, http.StatusNotFound)
	})

	t.Run("tags use client keys", func(t *testing.T) {
		const slug = "postgres"

		var created blog.Tag
		do(t, srv, http.MethodPost, "/tags", restapi.CreateTagRequest{Slug: slug, Label: "Postgres"}, &created, http.StatusCreated)
		require.Equal(t, blog.Tag{Slug: slug, Label: "Postgres", Color: "gray", Weight: 1}, created)

		do(t, srv, http.MethodPost, "/tags", restapi.CreateTagRequest{Slug: slug, Label: "Again"}, nil, http.StatusConflict)

		var got blog.Tag
		do(t, srv, http.MethodGet, "/tags/"+slug, nil, &got, http.StatusOK)
		require.Equal(t, created, got)
	})

	t.Run("down migrations drop the tables", func(t *testing.T) {
		require.NoError(t, goose.Reset(db.DB, "../internal/blog/migrations"), "goose reset (down)")
		_, err := db.Exec("SELECT 1 FROM posts")
		require.Error(t, err, "posts table should not exist after the down migrations")
	})
}

// startPostgres launches a throwaway PostgreSQL container and returns a DSN for
// it, registering termination as test cleanup.
func startPostgres(t *testing.T) string {
	t.Helper()
	ctx := context.Background()

	ctr, err := tcpostgres.Run(ctx, "postgres:16-alpine",
		tcpostgres.WithDatabase("blog"),
		tcpostgres.WithUsername("test"),
		tcpostgres.WithPassword("test"),
		testcontainers.WithWaitStrategy(
			wait.ForLog("database system is ready to accept connections").
				WithOccurrence(2).
				WithStartupTimeout(60*time.Second),
		),
	)
	require.NoError(t, err, "start postgres container")
	t.Cleanup(func() { require.NoError(t, testcontainers.TerminateContainer(ctr)) })

	dsn, err := ctr.ConnectionString(ctx, "sslmode=disable")
	require.NoError(t, err, "connection string")
	return dsn
}

type envelope struct {
	Body  jsontext.Value `json:"body"`
	Error jsontext.Value `json:"error"`
}

type offsetPage[T any] struct {
	Items   []T  `json:"items"`
	Limit   int  `json:"limit"`
	Offset  int  `json:"offset"`
	HasMore bool `json:"has_more"`
}

type cursorPage[T any] struct {
	Items      []T    `json:"items"`
	NextCursor string `json:"next_cursor"`
}

type apiError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// do issues a request, asserts the status code, and decodes the envelope into
// out when out is non-nil: its body on success, its error otherwise.
func do(t *testing.T, srv *httptest.Server, method, path string, body, out any, wantStatus int) {
	t.Helper()
	var r io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		require.NoError(t, err, "marshal body")
		r = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, srv.URL+path, r)
	require.NoError(t, err, "new request")

	resp, err := http.DefaultClient.Do(req)
	require.NoErrorf(t, err, "%s %s", method, path)
	defer func() { require.NoError(t, resp.Body.Close()) }()

	if resp.StatusCode != wantStatus {
		b, _ := io.ReadAll(resp.Body)
		require.Failf(t, "unexpected status",
			"%s %s: status = %d, want %d (body: %s)", method, path, resp.StatusCode, wantStatus, b)
	}
	if out == nil {
		return
	}
	var env envelope
	require.NoError(t, json.UnmarshalRead(resp.Body, &env), "decode response")
	payload := env.Body
	if wantStatus >= http.StatusBadRequest {
		payload = env.Error
	}
	require.NoError(t, json.Unmarshal(payload, out), "decode payload")
}
